In [1]:
import numpy as np
import scipy.optimize as opt

In [2]:
X = np.array([
    [20., 300., 50, 100],
    [30., 400., 5, 100],
    [40., 500., 50, 10],
    [50., 600., 5, 10],
    [60., 700., 50, 1],
    [70., 150., 5, 1],
    [80., 250., 50, 1],
    [90., 350., 5, 1],
    [100., 450., 50, 1],
    [110., 50., 5, 1],
])
y = np.array([
    [100., 120],
    [200., 50],
    [50., 100],
    [100., 200],
    [200., 100],
    [100., 20],
    [200., 50],
    [50., 100],
    [10., 200],
    [200., 100],
])


In [4]:
output_w =np.zeros(y.shape[1])
input_w = np.zeros(X.shape[1])
lambdas = np.zeros(X.shape[0])
efficiency = np.zeros_like(lambdas)

In [14]:
input_w

array([0., 0., 0., 0.])

In [15]:
output_w

array([0., 0.])

In [16]:
lambdas

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
efficiency

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
deminator= np.dot(X, input_w)
nominator = np.dot(y, output_w)


In [13]:
nominator


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# divide the nominator by the denominator
efficiency = nominator/deminator
efficiency

/tmp/ipykernel_61996/2040763059.py:1: RuntimeWarning: invalid value encountered in floor_divide
  efficiency = nominator//deminator


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [19]:
def __efficiency(inputs, outputs, unit):
        """
        Efficiency function with already computed weights
        :param unit: which unit to compute for
        :return: efficiency
        """

        # compute efficiency
        # denominator is sum of inputs data * input weights
        denominator = np.dot(inputs, input_w)
        # numerator is sum of outputs data * output weights
        numerator = np.dot(outputs, output_w)
        efficiency = numerator/denominator  # array of efficiencies
        # array of differences between numerator and denominator
        diff_unit = numerator-denominator

        return efficiency[unit]


def __target(weights, inputs, outputs, num_in,num_out,  unit):
        """
        Theta target function for one unit
        :param weights: combined weights (input, output, lambdas)
        :param unit: which production unit to compute
        :return: theta
        """
        in_w, out_w, lambdas = weights[:num_in], weights[num_in:(
            num_in+num_out)], weights[(num_in+num_out):]  # unroll the weights
        # denominator is sum of inputs data * input weights
        denominator = np.dot(inputs[unit], in_w)
        # numerator is sum of outputs data * output weights
        numerator = np.dot(outputs[unit], out_w)

        return numerator/denominator

In [22]:
weights=np.random.rand(X.shape[1]+y.shape[1]+X.shape[0])
len(weights)

16

In [ ]:
in_w, out_w, lambdas =

In [23]:
import numpy as np
from scipy.optimize import minimize


def objective(x):
    return x[0]*x[3]*(x[0]+x[1]+x[2])+x[2]
    return sum(descriptive)


def constraint1(x):
    return x[0]*x[1]*x[2]*x[3]-25.0


def constraint2(x):
    sum_eq = 40.0
    for i in range(4):
        sum_eq = sum_eq - x[i]**2
    return 


# initial guesses
n = 4
x0 = np.zeros(n)
x0[0] = 1.0
x0[1] = 5.0
x0[2] = 5.0
x0[3] = 1.0

# show initial objective
print('Initial Objective: ' + str(objective(x0)))

# optimize
b = (1.0, 5.0)
bnds = (b, b, b, b)
con1 = {'type': 'ineq', 'fun': constraint1}
con2 = {'type': 'eq', 'fun': constraint2}
cons = ([con1, con2])
solution = minimize(objective, x0, method='SLSQP',
                    bounds=bnds, constraints=cons)
x = solution.x

# show final objective
print('Final Objective: ' + str(objective(x)))

# print solution
print('Solution')
print('x1 = ' + str(x[0]))
print('x2 = ' + str(x[1]))
print('x3 = ' + str(x[2]))
print('x4 = ' + str(x[3]))


Initial Objective: 16.0
Final Objective: 17.01401724563517
Solution
x1 = 1.0
x2 = 4.742996096883977
x3 = 3.8211546234095715
x4 = 1.379407645075325


In [ ]:
def objective(weights,df)
    summ=sum()
